version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    ports:
      - ${SQL_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:${APP_PORT}
    volumes:
      - ./app:/code
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db