# Generated by Django 4.2.3 on 2023-08-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='telefone_principal',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='telefone_secundario',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
