# Generated by Django 4.2.3 on 2023-08-22 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_aluno_escola_evento_tipoevento_parente_notaevento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data',
        ),
        migrations.AddField(
            model_name='notaevento',
            name='data_entrega',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaevento',
            name='observacoes',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parente',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
