# Generated by Django 4.2.3 on 2023-08-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_alter_escola_telefone_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(choices=[('PRI', '1º ano'), ('SEG', '2º ano'), ('TER', '3º ano'), ('QUA', '4º ano'), ('QUI', '5º ano'), ('SEX', '6º ano'), ('SET', '7º ano'), ('OIT', '8º ano'), ('NON', '9º ano'), ('PEM', '1º E. M.'), ('SEM', '2º E. M.'), ('TEM', '3º E. M.')], max_length=3),
        ),
    ]
