# Generated by Django 4.2.3 on 2023-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0006_atividade_resultado_remove_notaevento_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='alergias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='info_adicionais',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='periodo',
            field=models.CharField(blank=True, choices=[('MAT', 'Matutino'), ('VES', 'Vespertino'), ('NOT', 'Noturno')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(blank=True, choices=[('PRI', '1º ano'), ('SEG', '2º ano'), ('TER', '3º ano'), ('QUA', '4º ano'), ('QUI', '5º ano'), ('SEX', '6º ano'), ('SET', '7º ano'), ('OIT', '8º ano'), ('NON', '9º ano'), ('PEM', '1º E. M.'), ('SEM', '2º E. M.'), ('TEM', '3º E. M.')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='vulnerabilidades',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='parente',
            name='info_adicionais',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='parente',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
