# Generated by Django 4.2.3 on 2023-10-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0007_aluno_alergias_alter_aluno_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
