# Generated by Django 4.2.3 on 2023-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0008_alter_aluno_cep_alter_aluno_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil_pais',
            field=models.CharField(choices=[('SOL', 'Solteiros'), ('CAS', 'Casados'), ('DIV', 'Divorciados'), ('VIU', 'Viúvos'), ('UNI', 'União Estável'), ('OUT', 'Outro')], max_length=3),
        ),
    ]
