# Generated by Django 4.2.3 on 2023-10-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0009_alter_aluno_estado_civil_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil_pais',
            field=models.CharField(blank=True, choices=[('SOL', 'Solteiros'), ('CAS', 'Casados'), ('DIV', 'Divorciados'), ('VIU', 'Viúvos'), ('UNI', 'União Estável'), ('OUT', 'Outro')], max_length=3, null=True),
        ),
    ]
