# Generated by Django 4.2.3 on 2023-10-06 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0010_alter_aluno_estado_civil_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='peso',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Peso deve ser no minimo 1'), django.core.validators.MaxValueValidator(100, 'Peso deve ser no maximo 100')]),
        ),
    ]
