# Generated by Django 4.2.3 on 2023-10-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0011_alter_atividade_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escolas.atividade'),
        ),
    ]
