# Generated by Django 4.2.3 on 2023-10-13 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0012_alter_resultado_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='parente',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0, 'Nota mínima é 0'), django.core.validators.MaxValueValidator(10, 'Nota máxima é 10')]),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='observacoes',
            field=models.CharField(max_length=100),
        ),
    ]
