# Generated by Django 4.2.3 on 2023-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0013_parente_cpf_alter_resultado_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parente',
            name='info_adicionais',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
