# Generated by Django 4.2.3 on 2023-10-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0014_alter_parente_info_adicionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='parente',
            name='grau_parentesco',
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_parentesco', models.CharField(choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('IRM', 'Irmãos'), ('AVO', 'Avós'), ('TIO', 'Tios'), ('PRI', 'Primos'), ('OUT', 'Outros')], max_length=3)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.aluno')),
                ('parente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.parente')),
            ],
        ),
    ]
