# Generated by Django 4.2.3 on 2023-10-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0015_remove_aluno_familia_remove_parente_grau_parentesco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentesco',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentescos', to='escolas.aluno'),
        ),
    ]
