# Generated by Django 4.2.3 on 2023-10-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0016_alter_parentesco_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parente',
            name='principal_responsavel',
        ),
        migrations.AddField(
            model_name='parentesco',
            name='principal_responsavel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='parente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentescos', to='escolas.parente'),
        ),
    ]
