# Generated by Django 4.2.6 on 2023-10-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ativo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(default='teste', max_length=50),
            preserve_default=False,
        ),
    ]
