# Generated by Django 4.2.6 on 2023-10-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_remove_customuser_ativo_customuser_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
